### ISSUE TITLE
Untustable curl statement

### ISSUE THREAD

**Issue by paul-hammant** [grosser/git-autobisect#4]
```
curl https://rubinjam.herokuapp.com/pack/git-autobisect ....
```

The `rubinjam` app could switch payloads based on user agent, IP address or anything hackers may think about.

This would not (we all trust GitHub's raw service far more):

```
curl https://raw.githubusercontent.com/grosser/git-autobisect/master/bin/git-autobisect ...
```

**Comment by grosser** [comment]
hmm good point ... it would be interesting to provide a "release" with each tag like other repos do tarballs

**Comment by paul-hammant** [comment]
Yup, and GH's raw interface allows you to implicate them directly too :)

**Comment by grosser** [comment]
that was fun :)

https://github.com/grosser/git-autobisect/commit/1850359b60f4119a2e2a27797fac4e7659ddcfdc

this should be a PR for `bump` and `rubinjam` ... but works for now ...
